import { StyleSheet } from "react-native";
import Colors from "@/constants/colors";

export const playerStyles = StyleSheet.create({
   container: {
      flex: 1,
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
   },
   background: {
      backgroundColor: "transparent",
   },
   sheetContent: {
      flex: 1,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      overflow: "hidden",
   },
   gradient: {
      flex: 1,
   },
   contentContainer: {
      flex: 1,
      paddingBottom: 34,
   },
   content: {
      flex: 1,
      paddingHorizontal: 24,
      justifyContent: "space-between",
      paddingBottom: 40,
   },
   header: {
      alignItems: "center",
      marginTop: 10,
      marginBottom: 20,
   },
   title: {
      fontSize: 30,
      color: Colors.light.text,
      fontWeight: "700",
      textAlign: "center",
      marginBottom: 4,
   },
   subtitle: {
      fontSize: 16,
      color: Colors.light.tabIconDefault,
      textAlign: "center",
   },
   artContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      maxHeight: 300,
      marginVertical: 20,
   },
   artWrapper: {
      borderRadius: 32,
      padding: 10,
      backgroundColor: Colors.light.surface,
      borderWidth: 1,
      borderColor: Colors.light.border,
      width: "105%",
      aspectRatio: 1.4,
   },
   art: {
      width: "100%",
      height: "100%",
      borderRadius: 26,
   },
   progressSection: {
      marginVertical: 24,
      gap: 8,
   },
   progressTrack: {
      height: 6,
      borderRadius: 999,
      backgroundColor: Colors.light.border,
      overflow: "hidden",
      justifyContent: "center",
   },
   progressFill: {
      position: "absolute",
      left: 0,
      top: 0,
      bottom: 0,
      backgroundColor: Colors.light.accent,
   },
   progressThumb: {
      position: "absolute",
      width: 16,
      height: 16,
      borderRadius: 16,
      backgroundColor: Colors.light.accent,
      top: -5,
      left: -8,
   },
   progressLabels: {
      flexDirection: "row",
      justifyContent: "space-between",
   },
   progressText: {
      color: Colors.light.tabIconDefault,
      fontSize: 14,
   },
   controlsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginVertical: 24,
   },
   iconButton: {
      alignItems: "center",
      gap: 4,
      padding: 8,
      minWidth: 50,
   },
   iconButtonPressed: {
      opacity: 0.6,
   },
   iconLabel: {
      fontSize: 11,
      color: Colors.light.tabIconDefault,
      marginTop: 2,
   },
   skipButton: {
      alignItems: "center",
      justifyContent: "center",
      width: 44,
      height: 44,
   },
   skipButtonPressed: {
      opacity: 0.6,
   },
   playButton: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: Colors.light.accent,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: Colors.light.accent,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
   },
   playButtonPressed: {
      transform: [{ scale: 0.96 }],
   },
   actionRow: {
      flexDirection: "row",
      gap: 16,
      marginTop: 20,
      justifyContent: 'center',
   },
   actionButton: {
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.15)',
      borderRadius: 24,
      paddingVertical: 18,
      paddingHorizontal: 16,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
   },
   actionButtonFavorite: {
      width: 180,
   },
   actionButtonSleep: {
      width: 180,
   },
   actionButtonPressed: {
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
   },
   actionButtonActive: {
      borderColor: Colors.light.accent,
      backgroundColor: 'rgba(59, 130, 246, 0.1)',
   },
   actionLabel: {
      color: Colors.light.text,
      fontSize: 15,
      fontWeight: "500",
   },
   actionLabelActive: {
      color: Colors.light.accent,
   },
   customHandle: {
      width: '100%',
      alignItems: 'center',
      paddingTop: 12,
      paddingBottom: 8,
   },
   handleIndicator: {
      backgroundColor: "rgba(255, 255, 255, 0.3)",
      width: 60,
      height: 4,
      borderRadius: 2,
   },
   sleepTimerModal: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
   },
   sleepTimerOptions: {
      backgroundColor: "rgba(0, 0, 0, 0.9)",
      borderRadius: 24,
      padding: 24,
      width: "80%",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.12)",
   },
   sleepTimerTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: Colors.light.text,
      marginBottom: 24,
      opacity: 0.8,
   },
   sleepTimerSubtitle: {
      fontSize: 16,
      color: Colors.light.tabIconDefault,
      marginBottom: 24,
      opacity: 0.8,
   },
   sleepTimerButtons: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      gap: 12,
      marginBottom: 20,
   },
   sleepTimerOption: {
      backgroundColor: Colors.light.accent,
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 16,
      minWidth: 100,
      alignItems: 'center',
   },
   sleepTimerCustomOption: {
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
      flexDirection: 'row',
      alignItems: 'center',
   },
   sleepTimerCustomSubmit: {
      minWidth: 150,
   },
   sleepTimerCustomSubmitDisabled: {
      opacity: 0.5,
      backgroundColor: 'rgba(59, 130, 246, 0.3)',
   },
   sleepTimerOptionPressed: {
      opacity: 0.8,
      backgroundColor: 'rgba(59, 130, 246, 0.8)',
   },
   sleepTimerOptionText: {
      color: Colors.light.accent,
      fontSize: 16,
      fontWeight: '600',
      opacity: 0.9,
   },
   sleepTimerCustomText: {
      color: Colors.light.text,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 16,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
   },
   sleepTimerCancelRight: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      paddingHorizontal: 34,
      borderRadius: 16,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.2)',
   },
   sleepTimerCancelText: {
      color: Colors.light.tabIconDefault,
      fontSize: 16,
      fontWeight: '600',
      opacity: 0.9,
   },
   sleepTimerCancelIcon: {
      marginLeft: 4,
   },
   sleepTimerBottomRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      width: '100%',
      marginTop: 20,
   },
   customTimerButtonsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 46,
      width: '100%',
   },
   customTimerInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 32,
      gap: 12,
   },
   customTimerInput: {
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
      borderRadius: 16,
      paddingVertical: 10,
      paddingHorizontal: 20,
      color: Colors.light.accent,
      fontSize: 32,
      fontWeight: '400',
      textAlign: 'center',
      minWidth: 100,
      opacity: 0.9,
   },
   customTimerLabel: {
      color: Colors.light.tabIconDefault,
      fontSize: 18,
      opacity: 0.8,
   },
});