import { StyleSheet } from "react-native";

export const favoritesStyles = StyleSheet.create({
    container: {
        flex: 1,
    },
    topGradientExtension: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 100,
        zIndex: 1,
    },
    safeArea: {
        flex: 1,
        zIndex: 2,
    },
    topBar: {
        paddingTop: 10,
        paddingHorizontal: 20,
        paddingBottom: 24,
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        gap: 16,
        shadowColor: "#000",
        shadowOpacity: 0.25,
        shadowRadius: 24,
        shadowOffset: { width: 0, height: 18 },
        elevation: 24,
    },
    headerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    headerContent: {
        flex: 1,
    },
    headerTitle: {
        color: "#FFFFFF",
        fontSize: 28,
        fontWeight: "800",
        lineHeight: 34,
        marginBottom: 6,
    },
    headerSubtitle: {
        color: "rgba(255,255,255,0.75)",
        fontSize: 14,
        fontWeight: "500",
        letterSpacing: 0.3,
    },
    scrollArea: {
        flex: 1,
        marginTop: 0,
    },
    listContent: {
        paddingHorizontal: 20,
        paddingBottom: 120,
        paddingTop: 20,
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 40,
        paddingTop: 60,
    },
    emptyTitle: {
        color: "#FFFFFF",
        fontSize: 20,
        fontWeight: "600",
        marginTop: 20,
        marginBottom: 8,
    },
    emptyText: {
        color: "rgba(255,255,255,0.6)",
        fontSize: 15,
        textAlign: 'center',
        lineHeight: 22,
    },
    swipeableContainer: {
        position: 'relative',
        overflow: 'hidden',
        borderRadius: 16,
    },
    deleteBackground: {
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 0,
        backgroundColor: '#FF3B30',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopRightRadius: 16,
        borderBottomRightRadius: 16,
    },
    deleteContent: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        width: 80,
    },
    deleteText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '600',
    },
    card: {
        borderRadius: 16,
        overflow: "hidden",
    },
    cardInner: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 14,
        paddingVertical: 14,
    },
    left: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        flexShrink: 1,
    },
    iconWrap: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: "center",
        justifyContent: "center",
    },
    cardTitle: {
        color: "#FFFFFF",
        fontSize: 15,
        fontWeight: "700",
        flexShrink: 1,
    },
    actions: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 12,
    },
    playButton: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    playContainer: {
        borderRadius: 12,
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        borderWidth: 1,
        borderColor: "rgba(255, 255,255, 0.1)",
        height: 36,
        paddingHorizontal: 16,
        alignItems: "center",
        justifyContent: "center",
        minWidth: 70,
    },
    playText: {
        color: "#FFFFFF",
        fontWeight: "800",
        fontSize: 13,
        letterSpacing: 0.2,
        textAlign: "center",
    },
    // Delete Confirmation Modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    confirmationBox: {
        backgroundColor: '#1A1A1A',
        borderRadius: 20,
        padding: 24,
        width: '100%',
        maxWidth: 320,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
    },
    confirmationIcon: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: 'rgba(255, 59, 48, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        marginBottom: 20,
    },
    confirmationTitle: {
        color: '#FFFFFF',
        fontSize: 20,
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 8,
    },
    confirmationMessage: {
        color: 'rgba(255,255,255,0.7)',
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 24,
    },
    confirmationButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    confirmationButton: {
        flex: 1,
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
    },
    deleteButton: {
        backgroundColor: '#FF3B30',
    },
    cancelButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    deleteButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
});