import { Platform, StyleSheet } from "react-native";

export const COLORS = {
    bgTop: "#05070B",
    bgBottom: "#0A0F16",
    cardTop: "rgba(255,255,255,0.07)",
    cardBottom: "rgba(255,255,255,0.03)",
    cardBorder: "rgba(255,255,255,0.10)",
    text: "rgba(255,255,255,0.92)",
    subText: "rgba(255,255,255,0.55)",
    inputBg: "rgba(8,12,18,0.35)",
    inputBorder: "rgba(255,255,255,0.16)",
    accent: "#FF8A3D",
    accentSoft: "rgba(255,138,61,0.20)",
    danger: "#FF5A52",
    dangerSoft: "rgba(255,90,82,0.16)",
} as const;

export const profileStyles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: COLORS.bgBottom,
    },
    safe: {
        backgroundColor: "transparent",
    },
    header: {
        paddingBottom: 24,
        paddingHorizontal: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    authContainer: {
        flexGrow: 1,
        paddingHorizontal: 24,
        paddingBottom: 40,
    },

    keyboardAvoidingView: {
        flex: 1,
    },
    avatarBlock: {
        alignItems: "center",
        paddingTop: 32,
        paddingBottom: 18,
        marginBottom: 10,
    },
    avatarCircle: {
        width: 220,
        height: 220,
        borderRadius: 90,
        backgroundColor: "rgba(255,255,255,0.08)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.14)",
        alignItems: "center",
        justifyContent: "center",
        position: "relative",
    },
    avatarInner: {
        width: 200,
        height: 200,
        borderRadius: 80,
        backgroundColor: "#F7B26B",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
    },
    editProfileButton: {
        marginTop: 12,
    },
    editableRow: {
        flex: 1,
        height: 44,
        color: COLORS.text,
        fontSize: 14,
        paddingVertical: 0,
        paddingHorizontal: 0,
    },
    editProfileButtonInner: {
        paddingVertical: 8,
        paddingHorizontal: 18,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        backgroundColor: "rgba(255,255,255,0.05)",
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },

    editProfileButtonText: {
        color: COLORS.accent,
        fontSize: 14,
        fontWeight: "600",
    },

    authTitle: {
        fontSize: 28,
        fontWeight: '800',
        color: COLORS.text,
        marginBottom: 8,
        textAlign: 'center',
    },
    authSubtitle: {
        fontSize: 16,
        color: COLORS.subText,
        textAlign: 'center',
        marginBottom: 32,
        lineHeight: 22,
        paddingHorizontal: 20,
    },
    formContainer: {
        gap: 20,
    },
    inputContainer: {
        gap: 8,
    },
    inputLabelRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        marginLeft: 4,
    },
    inputLabel: {
        color: COLORS.subText,
        fontSize: 13,
        fontWeight: "500",
    },
    inputFieldContainer: {
        height: 52,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: COLORS.inputBorder,
        backgroundColor: COLORS.inputBg,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
    },
    inputField: {
        flex: 1,
        color: COLORS.text,
        fontSize: 16,
        paddingVertical: 0,
        paddingHorizontal: 0,
        minHeight: 52,
    },
    modeSwitchContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        marginTop: 16,
    },
    modeSwitchText: {
        color: COLORS.subText,
        fontSize: 14,
    },
    modeSwitchLink: {
        color: COLORS.accent,
        fontSize: 14,
        fontWeight: "600",
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 10,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
    },
    sectionTitle: {
        marginTop: 10,
        marginBottom: 8,
        color: "rgba(255,255,255,0.60)",
        fontSize: 12,
        letterSpacing: 0.2,
    },
    card: {
        borderRadius: 14,
        padding: 12,
        borderWidth: 1,
        borderColor: COLORS.cardBorder,
        overflow: "hidden",
        marginBottom: 10,
    },
    cardTopHighlight: {
        position: "absolute",
        left: -40,
        right: -40,
        top: -80,
        height: 140,
        backgroundColor: "rgba(255,255,255,0.06)",
        transform: [{ rotate: "-8deg" }],
    },
    fieldBlock: {
        width: "100%",
        marginBottom: 24,
    },
    fieldLabel: {
        color: "rgba(255,255,255,0.55)",
        fontSize: 11,
        marginBottom: 6,
        marginLeft: 4,
    },
    inputRow: {
        height: 44,
        borderRadius: 12,
        borderWidth: 1,
        backgroundColor: COLORS.inputBg,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 10,
    },
    inputRowFocused: {
        shadowColor: COLORS.accent,
        shadowOpacity: 0.18,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 6 },
        elevation: 4,
    },
    inputRowError: {
        backgroundColor: COLORS.dangerSoft,
    },
    inputIcon: {
        marginRight: 12,
        color: "rgba(255,255,255,0.80)",
    },
    inputFieldIcon: {
        marginRight: 12,
        color: COLORS.subText,
    },
    input: {
        flex: 1,
        color: COLORS.text,
        fontSize: 14,
        paddingVertical: 10,
        paddingHorizontal: 0,
        minHeight: 44,
    },
    errorRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 4,
        marginTop: 6,
    },
    errorAsterisk: {
        color: COLORS.danger,
        fontSize: 14,
        fontWeight: "700",
        lineHeight: 14,
        marginTop: 2,
    },
    errorText: {
        color: COLORS.danger,
        fontSize: 11,
    },
    authErrorContainer: {
        marginTop: 20,
        alignItems: "center",
        justifyContent: "center",
    },

    authErrorText: {
        color: COLORS.danger,
        fontSize: 13,
        textAlign: "center",
        lineHeight: 18,
    },
    securityCard: {
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    securityRowContainer: {
        width: '100%',
    },
    securityRowSpacer: {
        marginTop: 10,
    },
    securityRow: {
        height: 44,
        borderRadius: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 10,
        backgroundColor: "rgba(8,12,18,0.22)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.10)",
    },
    securityLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
    },
    securityIconWrap: {
        width: 28,
        height: 28,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.accentSoft,
    },
    securityText: {
        color: COLORS.text,
        fontSize: 14,
        fontWeight: "600",
    },
    primaryButtonContainer: {
        width: '100%',
        marginTop: 14,
    },
    primaryButton: {
        height: 48,
        borderRadius: 14,
        backgroundColor: COLORS.accent,
        alignItems: "center",
        justifyContent: "center",
        shadowColor: COLORS.accent,
        shadowOpacity: 0.30,
        shadowRadius: 16,
        elevation: 8,
    },
    primaryButtonText: {
        color: "#141414",
        fontSize: 15,
        fontWeight: "800",
        letterSpacing: 0.2,
    },
    secondaryButtonContainer: {
        width: '100%',
        marginTop: 10,
    },
    secondaryButton: {
        height: 48,
        borderRadius: 14,
        backgroundColor: "rgba(0,0,0,0.00)",
        borderWidth: 1,
        borderColor: "rgba(255,138,61,0.65)",
        alignItems: "center",
        justifyContent: "center",
    },
    secondaryButtonText: {
        color: COLORS.accent,
        fontSize: 15,
        fontWeight: "700",
        letterSpacing: 0.2,
    },
    buttonDisabled: {
        opacity: 0.7,
    },
    btnPressed: {
        transform: [{ scale: 0.98 }],
        opacity: 0.90,
    },
    bottomSpacer: {
        height: Platform.OS === 'ios' ? 40 : 20,
    },
});